dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path("", views.index, name="index"),
    path("profile", views.Profile, name="profile"),
    path("cancel-membership", views.CancelMembership, name="cancel-membership"),
    path("upgrade-membership", views.UpgradeMembership, name="upgrade-membership"),
    # path("your-business-report", views.YourBusinessReport, name="your-business-report"),
    path("dispute", views.DisputeView, name="dispute"),
    path(
        "your-company-information",
        views.YourCompanyInformation,
        name="your-company-information",
    ),
    path(
        "add-business-tradelines",
        views.AddBusinessTradelines,
        name="add-business-tradelines",
    ),
    path(
        "update-company-information",
        views.UpdateCompanyInformation,
        name="update-company-information",
    ),
    path(
        "business-credit-reports",
        views.BusinessCreditReports,
        name="business-credit-reports",
    ),
    path(
        "current-business-tradelines",
        views.CurrentBusinessTradelines,
        name="current-business-tradelines",
    ),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('',views.index,name='home'),
  path('services',views.Services,name='services'),
  path('about',views.About,name='about'),
  path('contact',views.Contact,name='contact'),
  path('register/<int:id>/',views.AccountWithPay,name='register'),
  path('make_payment/<int:id>/',views.MakePaymentView,name='make_payment'),
  path('config/', views.stripe_config),
  path('success/', views.Success),
  path('create-checkout-session/<int:id>/', views.MakePayment),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from . import views
app_name = "users"
urlpatterns = [
    path('logout/', views.Logout, name='logout'),
    path('login/', views.Login, name='login'),
    path('sign-up/', views.SignUp, name='signup'),
    path('edit-profile/', views.EditProfile, name='edit-profile'),
    path('change-password/', views.ChangePassword, name='change-password'),
    path('reset_password/', PasswordResetView.as_view(
        template_name='reset_password.html'), name='reset_password'),
    path('reset_password_sent/', PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

ziteso/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('auth/', include('users.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class CompanyInformation(models.Model):
    """
    Company information
    """
    ziteso_number = models.CharField(max_length=100)
    email = models.EmailField()
    anual_sales = models.CharField(max_length=100)
    business_form = models.CharField(max_length=100)
    telephone = models.CharField(max_length=100)
    employees = models.CharField(max_length=100)
    date_incorporated = models.DateTimeField(auto_now_add=False,auto_now=True)
    age = models.CharField(max_length=100)
    state_incorporated = models.CharField(max_length=100)
    name_of_principle = models.CharField(max_length=100)
    business_name = models.CharField(max_length=100)
    business_address = models.CharField(max_length=100)
    judgements = models.CharField(max_length=100)
    liens = models.CharField(max_length=100)
    suits = models.CharField(max_length=100)
    ucc_filings = models.CharField(max_length=100)
    special_events = models.CharField(max_length=100)
    company_events = models.CharField(max_length=100)
    profit_and_loss = models.CharField(max_length=100)
    total_number_of_enquiries = models.IntegerField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class YourBusinessRecommendation(models.Model):
    """
    Business recommendation
    """
    name = models.CharField(max_length=100,default='You Do Not Have Any Current Recommendations')
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class YourCurrentTradelines(models.Model):
    """
    Current TradeLines
    """
    business_name = models.CharField(max_length=100,default='You Do Not Have Any Current TradeLines')
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    tradeline_age = models.CharField(max_length=100)
    tradeline_date = models.DateField(auto_now=False,auto_now_add=False)
    tradeline_amount = models.IntegerField()
    status = models.CharField(choices=(('pending','pending'),('confirmed','confirmed')),max_length=100,default="pending")
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.business_name

class ZitesoBusinessIntelligenceScore(models.Model):
    """
    Sendesta Score
    """
    score = models.IntegerField()
    maximum_credit_recommendation = models.IntegerField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class BusinessReports(models.Model):
    """
    Business Reports
    """
    business_name = models.CharField(max_length=100)
    report = models.CharField(max_length=100)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.business_name

class UpdateYourCompanyInformation(models.Model):
    """
    Update Your Company Information
    """
    business_address = models.CharField(max_length=100)
    anual_sales = models.CharField(max_length=100)
    telephone = models.CharField(max_length=100)
    employees = models.CharField(max_length=100)
    line_of_business = models.CharField(max_length=100)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Dispute(models.Model):
    """
    Dispute
    """
    business_name = models.CharField(max_length=100)
    business_email = models.EmailField()
    business_phone = models.CharField(max_length=100)
    reason_of_dispute = models.CharField(max_length=500)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.business_name

class ZitesoScore(models.Model):
    """
    Sendesta Score
    """
    score = models.IntegerField()
    maximum_credit_recommendation = models.IntegerField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

dashboard/views.py
from django.shortcuts import render , redirect
from django.contrib import messages
from users.models import UserProfile
from django.contrib.auth.decorators import login_required
from .models import (CompanyInformation
,YourBusinessRecommendation
,YourCurrentTradelines
,ZitesoBusinessIntelligenceScore
,BusinessReports
,UpdateYourCompanyInformation,
Dispute,ZitesoScore)

# Create your views here.

@login_required
def index(request):
  score = ZitesoScore.objects.filter(user=request.user).first()
  recommendation = YourBusinessRecommendation.objects.filter(user=request.user)
  context = {}
  context['score'] = score
  context['recommendation'] = recommendation
  return render(request, 'dashboard/index.html',context)

@login_required
def Profile(request):
  context = {}
  user_profile, _ = UserProfile.objects.get_or_create(user=request.user)
  context['user_profile'] = user_profile
  if request.method == 'POST':
    full_name = request.POST.get('full_name')
    email = request.POST.get('email')
    phone = request.POST.get('phone')
    password = request.POST.get('password')
    country = request.POST.get('country')
    user = request.user
    user.first_name = full_name
    user.email = email
    user_profile.phone = phone
    user_profile.country = country
    user.set_password(password)
    user_profile.save()
    user.save()
    messages.success(request, 'Your profile has been updated.')
  return render(request, 'dashboard/userprofile.html',context)

# @login_required
# def YourBusinessReport(request):
#   context = {}
#   reports = BusinessReports.objects.filter(user=request.user)
#   context['reports'] = reports
#   return render(request, 'business-credit-report.html',context)

@login_required
def BusinessCreditReports(request):
  reports = BusinessReports.objects.filter(user=request.user)
  context = {}
  context['reports'] = reports
  score = ZitesoBusinessIntelligenceScore.objects.filter(user=request.user).first()
  context['score'] = score
  company = CompanyInformation.objects.filter(user=request.user).first()
  context['company'] = company
  tradelines = YourCurrentTradelines.objects.filter(user=request.user)
  context['tradelines'] = tradelines
  return render(request, 'dashboard/business-credit-report.html',context)

@login_required
def YourCompanyInformation(request):
  company = CompanyInformation.objects.filter(user=request.user).first()
  context = {}
  context['company'] = company
  return render(request, 'dashboard/view-company-information.html',context)

@login_required
def AddBusinessTradelines(request):
  tradelines = YourCurrentTradelines.objects.filter(user=request.user)
  context = {}
  context['tradelines'] = tradelines
  return render(request, 'dashboard/addbusinesstradelines.html',context)

@login_required
def DisputeView(request):
  context = {}
  if request.method == 'POST':
    business_name = request.POST.get('business_name')
    business_email = request.POST.get('business_email')
    business_phone = request.POST.get('business_phone')
    reason_of_dispute = request.POST.get('reason_of_dispute')
    Dispute.objects.create(
      business_name = business_name,
      business_email = business_email,
      business_phone = business_phone,
      reason_of_dispute = reason_of_dispute)
  tradelines = YourCurrentTradelines.objects.filter(user=request.user)
  context['tradelines'] = tradelines
  return render(request, 'dashboard/dispute-business-report.html',context)

@login_required
def UpdateCompanyInformation(request):
  context = {}
  company  = UpdateYourCompanyInformation.objects.filter(user=request.user).first()
  context['company'] = company
  return render(request, 'dashboard/update-company-information.html',context)


@login_required
def CurrentBusinessTradelines(request):
  context = {}
  tradelines = YourCurrentTradelines.objects.filter(user=request.user)
  context['tradelines'] = tradelines
  return render(request, 'dashboard/view-current-business-tradelines.html',context)

@login_required
def CancelMembership(request):
  request.user.userprofile.paid = False
  request.user.userprofile.save()
  return redirect('/dashboard/')

@login_required
def UpgradeMembership(request):
  return redirect('/')

dashboard/templates/dashboard/business-credit-report.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-xl-6">
    <div class="row">
      <div class="col-xl-12">
        <div class="card">
          <div class="card-body">
            <div class="row ">
              <div class="col-xl-8 col-xxl-7 col-sm-7">
                <div class="update-profile d-flex">
                  <img src="{% static 'dashboard/images/profile/pic1.jpg' %}" alt="">
                  <div class="ms-4">
                    <h3 class="fs-24 font-w600 mb-0">{{request.user.username}}</h3>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-xxl-5 col-sm-5 sm-mt-auto mt-3">
                <a href="javascript:void(0);" class="btn btn-primary btn-rounded">Update Profile</a>
              </div>
            </div>
            <div class="row mt-4 align-items-center">
              <h4 class="fs-20 mb-3"> Payment History</h4>
              <div class="col-xl-6 col-sm-6">
                <div class="progress default-progress">
                  <div class="progress-bar bg-green progress-animated" style="width: 90%; height:13px;"
                    role="progressbar">
                    <span class="sr-only">90% </span>
                  </div>
                </div>
                <div class="d-flex align-items-end mt-2 pb-4 justify-content-between">
                  <span class="fs-14 font-w500">Employee Number & Annual Sales</span>
                  <span class="fs-16"><span class="text-black pe-2"></span>90%</span>
                </div>
                <div class="progress default-progress">
                  <div class="progress-bar bg-info progress-animated" style="width: 68%; height:13px;"
                    role="progressbar">
                    <span class="sr-only">45% </span>
                  </div>
                </div>
                <div class="d-flex align-items-end mt-2 pb-4 justify-content-between">
                  <span class="fs-14 font-w500">Open Credit</span>
                  <span class="fs-16"><span class="text-black pe-2"></span>68%</span>
                </div>
                <div class="progress default-progress">
                  <div class="progress-bar bg-blue progress-animated" style="width: 85%; height:13px;"
                    role="progressbar">
                    <span class="sr-only">85% </span>
                  </div>
                </div>
                <div class="d-flex align-items-end mt-2 pb-4 justify-content-between">
                  <span class="fs-14 font-w500"> Business Age</span>
                  <span class="fs-16"><span class="text-black pe-2"></span>85%</span>
                </div>
              </div>
              <div class="col-xl-6 col-sm-6">
                <p>Maximum Business Recommendation</p>
                <p>{{score.maximum_credit_recommendation}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="nk-content">
  <div class="container-fluid">
    <div class="row page-header">
      <div class="col-lg-6 align-self-center">
        <h2>View Your Credit Report</h2>
      </div>

    </div>
    <br />
    <section class="main-content">
      <div class="card card-bordered h-100">
        <div class="card-inner mb-n2">
          <div class="card-title-group">
            <div class="card-title card-title">
              <h6 class="title"> </h6>
            </div>

          </div>
        </div>
        <div class="nk-tb-list is-loose traffic-channel-table">
          <table class="table table-lg">
            <tr>
              <th>Business name</th>
              <th>Email</th>
              <th>Phone</th>
              <th>Tradeline age</th>
              <th>Tradeline date</th>
              <th>Tradeline amount</th>
              <th>Status</th>
            </tr>
            {% for x in tradelines %}
            <tr>
              <td>{{x.business_name}}</td>
              <td>{{x.email}}</td>
              <td>{{x.phone}}</td>
              <td>{{x.tradeline_age}}</td>
              <td>{{x.tradeline_date}}</td>
              <td>{{x.tradeline_amount}}</td>
              <td>{{x.status}}</td>
            </tr>
            {% endfor %}
          </table>
          <!-- .nk-tb-item -->
        </div>
        <!-- .nk-tb-list -->
      </div>
  </div>


  </section>
</div>

{% endblock content %}

dashboard/templates/dashboard/register.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head> {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content="" />
  <meta name="author" content="" />
  <meta name="robots" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Jobick : Job Admin Bootstrap 5 Template" />
  <meta property="og:title" content="Jobick : Job Admin Bootstrap 5 Template" />
  <meta property="og:description" content="Jobick : Job Admin Bootstrap 5 Template" />
  <meta property="og:image" content="https://jobick.dexignlab.com/xhtml/social-image.png" />
  <meta name="format-detection" content="telephone=no">

  <!-- PAGE TITLE HERE -->
  <title>Ziteso Register</title>

  <!-- FAVICONS ICON -->
  <link rel="shortcut icon" type="image/png" href="images/favicon.png" />
  <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">

</head>

<body class="vh-100" id="Vueapp">
  <header>
    <!--Navigation-->
    <nav class="navbar navbar-default menu-nav" id="main_navbar">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'main/image/favicon.png' %}" width="50%" height="50%"alt=""></a>
        </div>  
      </div>
    </nav>
  </header>

  <div class="authincation h-100">
    <div class="container h-100">
      <div class="row justify-content-center h-100 align-items-center">
        <div class="col-md-6">
          <div class="authincation-content">
            <div class="row no-gutters">
              <div class="col-xl-12">
                <div class="auth-form">
                  <div class="text-center mb-3">
                    <a href="index.html"><img src="images/logo-full.png" alt=""></a>
                  </div>
                  <h4 class="text-center mb-4">Sign up your account</h4>
                  <form method="post" action="{% url 'users:signup' %}"> {% csrf_token %}
                    <div class="mb-3">
                      <label class="mb-1"><strong>Username</strong></label>
                      <input v-model="username" name="username" type="text" class="form-control" placeholder="username">
                    </div>
                    <div class="mb-3">
                      <label class="mb-1"><strong>Email</strong></label>
                      <input v-model="email" name="email" type="email" class="form-control" placeholder="hello@example.com">
                    </div>
                    <div class="mb-3">
                      <label class="mb-1"><strong>Password</strong></label>
                      <input v-model="password" name="password" type="password" class="form-control" value="Password">
                    </div>
                    <div class="text-center mt-4">
                      <button type="submit" class="btn btn-primary btn-block">Sign me up</button>
                    </div>
                  </form>
                  <div class="new-account mt-3">
                    <p>Already have an account? <a class="text-primary" href="{% url 'users:login' %}">Sign
                        in</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!--**********************************
	Scripts
***********************************-->
  <!-- Required vendors -->
  <script src="{% static 'dashboard/vendor/global/global.min.js' %}"></script>
  <script src="{% static 'dashboard/js/custom.min.js' %}"></script>
  <script src="{% static 'dashboard/js/dlabnav-init.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
 
</body>

</html>